services:
  redis:
    image: redis:alpine
    container_name: logvizpro_redis
    ports:
      - "6379:6379"
    networks:
      - logviz_net

  log-collector:
    build: ./services/log-collector
    container_name: logvizpro_collector
    environment:
      PORT: 3001
      MONGO_URI: mongodb://host.docker.internal:27017/logvizpro  # ✅ Access host MongoDB
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - logviz_net
    extra_hosts:
      - "host.docker.internal:host-gateway"  # ✅ Required for Linux

  log-analyzer:
    build: ./services/log-analyzer
    container_name: logvizpro_analyzer
    environment:
      PORT: 8000
      MONGO_URI: mongodb://host.docker.internal:27017/logvizpro  # ✅ Access host MongoDB
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - logviz_net
    extra_hosts:
      - "host.docker.internal:host-gateway"  # ✅ Required for Linux

  visualizer:
    build: ./visualizer
    container_name: logvizpro_frontend
    ports:
      - "5173:80"
    depends_on:
      - log-collector
      - log-analyzer
    networks:
      - logviz_net

networks:
  logviz_net:
    driver: bridge